apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Release.Name }}-vault
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vault
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vault
    spec:
      containers:
      - name: vault
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "server"
          - "-dev"   # ⚠️ dev mode for demo only
        ports:
        - containerPort: 8200
