apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-vault
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8200
      name: http
